names = ["Bob", "Kevin", "Richard", "Robin", "Jeremy", "Jeremy"]
print(names[1])
print(names[-1])
print(names[1:])
print(names[2:4])
names[1] = "Hippo"
print(names[0:3])
names.sort()
print(names)
numbers = [1, 5, 8, 164]
names2 = names.copy()
names.extend(numbers)
print(names)
names.append("Tim")
print(names)
names.insert(2, "Karen")
print(names)
names.remove("Hippo")
print(names)
names.pop()
print(names)
print(names.index("Richard"))
print(names.count("Jeremy"))
names.clear()
print(names)
numbers.reverse()
print(numbers)
print(names2)

print("tuples are like lists but cant be modified (immutable)")
coordinates = (6, 9)
print(coordinates)
print(coordinates[0])
coordinates2 = [(6, 5), (7, 8), (5, 4)]
print(coordinates2)