print("Hi")
print("  /|")
print(" / |")
print("/__|")
character_name = "Bob"
character_age = "21"
is_male = True
print("hi my name is " + character_name + " I am " + character_age + " years old")
character_name = "Alex"
print("But i really like the name " + character_name)
print("How\nare\nyou?")
print("to say \" u need a \ before it")
phrase = "Gotta Catch Em All"
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print("This is the length of the phrase")
print(len(phrase))
print(phrase[0])
print(phrase.index("h"))
print(phrase.index("Em All"))
print(phrase.replace("Em", "Them"))
print("39:08")
print(3)
print(3+5*9/4)
print((3+5)*9/4)
print("reminder for 11/3 is")
print(11 % 3)
Cool_num = 158
print(Cool_num)
print(str(Cool_num)+" is cool also a string")
interesting_num = -15.1
print(abs(interesting_num))
print(pow(4, 3))
print(max(3, 5))
print(max(3 * 3, 5 * 2))
print(min(3, 5))
print(min(3 * 3, 5 * 2))
print(round(3.7))
print("we can import stuff")
from math import *
print(floor(3.7))
print(ceil(3.4))
print(sqrt(49))
Name = input("Enter your name: ")
Age = input("Enter your age: ")
Pass = input("Enter your password: ")
print("Hello " + Name)
print("You are " + Age + " years old")
print("And this is your password: " + Pass)
num1 = input("Enter a whole number: ")
num2 = input("Enter a decibel number: ")
result = int(num1) + float(num2)
print(result)
